version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: fitness-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - fitness-app-network

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: fitness-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=fitness_app
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - fitness-app-network
    ports:
      - "5174:5174"
      - "8080:8080"


  mysql:
    image: mysql:8.0
    container_name: fitness-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fitness_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fitness-app-network

  redis:
    image: redis:alpine
    container_name: fitness-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fitness-app-network

volumes:
  mysql_data:
    driver: local

networks:
  fitness-app-network:
    driver: bridge
